[project]
name = "new-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Utkarsh Roy", email = "prashantsinghsingh2009@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=1.1.3",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
]

[project.scripts]
new-folder = "new_folder:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
